/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersListRouteImport } from './routes/orders/list'
import { Route as OrdersDetailRouteImport } from './routes/orders/detail'
import { Route as OrdersCreateRouteImport } from './routes/orders/create'
import { Route as MedicationListRouteImport } from './routes/medication/list'
import { Route as MedicationIdRouteImport } from './routes/medication/$id'
import { Route as CheckoutOpenRouteImport } from './routes/checkout/open'
import { Route as CheckoutCloseRouteImport } from './routes/checkout/close'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersListRoute = OrdersListRouteImport.update({
  id: '/orders/list',
  path: '/orders/list',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersDetailRoute = OrdersDetailRouteImport.update({
  id: '/orders/detail',
  path: '/orders/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersCreateRoute = OrdersCreateRouteImport.update({
  id: '/orders/create',
  path: '/orders/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationListRoute = MedicationListRouteImport.update({
  id: '/medication/list',
  path: '/medication/list',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationIdRoute = MedicationIdRouteImport.update({
  id: '/medication/$id',
  path: '/medication/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOpenRoute = CheckoutOpenRouteImport.update({
  id: '/checkout/open',
  path: '/checkout/open',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCloseRoute = CheckoutCloseRouteImport.update({
  id: '/checkout/close',
  path: '/checkout/close',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/close': typeof CheckoutCloseRoute
  '/checkout/open': typeof CheckoutOpenRoute
  '/medication/$id': typeof MedicationIdRoute
  '/medication/list': typeof MedicationListRoute
  '/orders/create': typeof OrdersCreateRoute
  '/orders/detail': typeof OrdersDetailRoute
  '/orders/list': typeof OrdersListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/close': typeof CheckoutCloseRoute
  '/checkout/open': typeof CheckoutOpenRoute
  '/medication/$id': typeof MedicationIdRoute
  '/medication/list': typeof MedicationListRoute
  '/orders/create': typeof OrdersCreateRoute
  '/orders/detail': typeof OrdersDetailRoute
  '/orders/list': typeof OrdersListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/close': typeof CheckoutCloseRoute
  '/checkout/open': typeof CheckoutOpenRoute
  '/medication/$id': typeof MedicationIdRoute
  '/medication/list': typeof MedicationListRoute
  '/orders/create': typeof OrdersCreateRoute
  '/orders/detail': typeof OrdersDetailRoute
  '/orders/list': typeof OrdersListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout/close'
    | '/checkout/open'
    | '/medication/$id'
    | '/medication/list'
    | '/orders/create'
    | '/orders/detail'
    | '/orders/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout/close'
    | '/checkout/open'
    | '/medication/$id'
    | '/medication/list'
    | '/orders/create'
    | '/orders/detail'
    | '/orders/list'
  id:
    | '__root__'
    | '/'
    | '/checkout/close'
    | '/checkout/open'
    | '/medication/$id'
    | '/medication/list'
    | '/orders/create'
    | '/orders/detail'
    | '/orders/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutCloseRoute: typeof CheckoutCloseRoute
  CheckoutOpenRoute: typeof CheckoutOpenRoute
  MedicationIdRoute: typeof MedicationIdRoute
  MedicationListRoute: typeof MedicationListRoute
  OrdersCreateRoute: typeof OrdersCreateRoute
  OrdersDetailRoute: typeof OrdersDetailRoute
  OrdersListRoute: typeof OrdersListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/list': {
      id: '/orders/list'
      path: '/orders/list'
      fullPath: '/orders/list'
      preLoaderRoute: typeof OrdersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/detail': {
      id: '/orders/detail'
      path: '/orders/detail'
      fullPath: '/orders/detail'
      preLoaderRoute: typeof OrdersDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/create': {
      id: '/orders/create'
      path: '/orders/create'
      fullPath: '/orders/create'
      preLoaderRoute: typeof OrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medication/list': {
      id: '/medication/list'
      path: '/medication/list'
      fullPath: '/medication/list'
      preLoaderRoute: typeof MedicationListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medication/$id': {
      id: '/medication/$id'
      path: '/medication/$id'
      fullPath: '/medication/$id'
      preLoaderRoute: typeof MedicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/open': {
      id: '/checkout/open'
      path: '/checkout/open'
      fullPath: '/checkout/open'
      preLoaderRoute: typeof CheckoutOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/close': {
      id: '/checkout/close'
      path: '/checkout/close'
      fullPath: '/checkout/close'
      preLoaderRoute: typeof CheckoutCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutCloseRoute: CheckoutCloseRoute,
  CheckoutOpenRoute: CheckoutOpenRoute,
  MedicationIdRoute: MedicationIdRoute,
  MedicationListRoute: MedicationListRoute,
  OrdersCreateRoute: OrdersCreateRoute,
  OrdersDetailRoute: OrdersDetailRoute,
  OrdersListRoute: OrdersListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
