/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutOpenRouteImport } from './routes/checkout/open'
import { Route as CheckoutCloseRouteImport } from './routes/checkout/close'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOpenRoute = CheckoutOpenRouteImport.update({
  id: '/checkout/open',
  path: '/checkout/open',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCloseRoute = CheckoutCloseRouteImport.update({
  id: '/checkout/close',
  path: '/checkout/close',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/close': typeof CheckoutCloseRoute
  '/checkout/open': typeof CheckoutOpenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/close': typeof CheckoutCloseRoute
  '/checkout/open': typeof CheckoutOpenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/close': typeof CheckoutCloseRoute
  '/checkout/open': typeof CheckoutOpenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout/close' | '/checkout/open'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout/close' | '/checkout/open'
  id: '__root__' | '/' | '/checkout/close' | '/checkout/open'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutCloseRoute: typeof CheckoutCloseRoute
  CheckoutOpenRoute: typeof CheckoutOpenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/open': {
      id: '/checkout/open'
      path: '/checkout/open'
      fullPath: '/checkout/open'
      preLoaderRoute: typeof CheckoutOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/close': {
      id: '/checkout/close'
      path: '/checkout/close'
      fullPath: '/checkout/close'
      preLoaderRoute: typeof CheckoutCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutCloseRoute: CheckoutCloseRoute,
  CheckoutOpenRoute: CheckoutOpenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
